; Robomates Base Firmware - PlatformIO Configuration

[env]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
board_build.partitions = max_app_4MB.csv
build_type = debug
build_flags = 
	-D CORE_DEBUG_LEVEL=5
	-D CONFIG_BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN=2
	-D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2
	-g3
	-ggdb
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, log2file, time
platform_packages = 
	framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
	fastled/FastLED@^3.10.1

[env:base]
