; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ===== Shared configuration =====
[env]
platform = espressif32@6.10.0
board = esp32dev
framework = arduino
board_build.partitions = max_app_4MB.csv
build_type = debug
build_flags = 
	-D CORE_DEBUG_LEVEL=5
	-D CONFIG_BTDM_CONTROLLER_BR_EDR_MAX_ACL_CONN=2
	-D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2
	-g3
	-ggdb
	-fno-omit-frame-pointer
	-fno-optimize-sibling-calls
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder, log2file, time
platform_packages = 
	framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip
lib_deps = 
	askuric/Simple FOC@2.3.2
	fastled/FastLED@^3.10.1
	sparkfun/SparkFun ATECCX08a Arduino Library@^1.3.1
	adafruit/Adafruit TMP117@^1.0.3

[env:robomate_868]
lib_ignore = RadioLib@*

[env:robomate_915]
lib_ignore = RadioLib@*
build_flags = 
	${env.build_flags}
	-D CC1101_FREQUENCY=915.0

[env:robomate_470]
lib_ignore = RadioLib@*
build_flags = 
	${env.build_flags}
	-D CC1101_FREQUENCY=470.0

[env:robomate_subghz_disabled]
lib_ignore = RadioLib@*
build_flags = 
	${env.build_flags}
	-D DISABLE_CC1101=true
